model_name_or_path: Qwen/Qwen2-7B-Instruct
tokenizer_name_or_path: Qwen/Qwen2-7B-Instruct
cache_dir: null
trust_remote_code: false
num_labels: 2
device_map: null
padding_side: right
use_custom_binary_head: false
attn_implementation: null
head_trainable_patterns:
  - classifier
  - score
  - head
